version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - unparam

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    enable:
      - shadow

formatters-settings:
  goimports:
    local-prefixes:
      - github.com/kikokikok/provider-garage

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
    - path: zz_generated\.deepcopy\.go
      linters:
        - all
  exclude-dirs:
    - vendor
    - bin

run:
  timeout: 5m

output:
  formats:
    text:
      path: stdout
