linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - unparam

linters-settings:
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/kikokikok/provider-garage
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: zz_generated\.deepcopy\.go
      linters:
        - all
  exclude-dirs:
    - vendor
    - bin

run:
  timeout: 5m

output:
  format: colored-line-number
