linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - unparam

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/kikokikok/provider-garage
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: zz_generated\.deepcopy\.go
      linters:
        - all

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - bin
  skip-files:
    - ".*\\.pb\\.go$"
    - "zz_generated\\..*\\.go$"
