linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - unparam
    - gofmt
    - goimports

linters-settings:
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/kikokikok/provider-garage

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
    - path: zz_generated\.deepcopy\.go
      linters:
        - all
  exclude-dirs:
    - vendor
    - bin

run:
  timeout: 5m
