// Package controller contains setup logic for controllers.
package controller

import (
	ctrl "sigs.k8s.io/controller-runtime"

	"github.com/crossplane/crossplane-runtime/pkg/controller"
)

// Setup creates all controllers with the supplied logger and adds them to
// the supplied manager.
func Setup(mgr ctrl.Manager, o controller.Options) error {
	// Controllers will be generated by upjet and registered here
	// This is a placeholder that will be replaced during code generation
	return nil
}
