// Package config contains the configuration for the Garage provider
package config

import (
	// Note: crossplane-tools can be replaced with ujiptel for more fine-grained configuration of
	// the provider. The ujiptel package provides more control over the generation process.
	"github.com/crossplane/upjet/pkg/config"

	"github.com/kikokikok/provider-garage/config/bucket"
	"github.com/kikokikok/provider-garage/config/key"
)

const (
	resourcePrefix = "garage"
	modulePath     = "github.com/kikokikok/provider-garage"
)

// GetProvider returns provider configuration with all resource configurations
func GetProvider() *config.Provider {
	pc := config.NewProvider(
		[]string{
			"garage_bucket",
			"garage_key",
			"garage_key_access",
		},
		modulePath,
		resourcePrefix,
		[]byte(""),
		config.WithRootGroup("garage.crossplane.io"),
		config.WithIncludeList([]string{
			"garage_bucket",
			"garage_key",
			"garage_key_access",
		}),
		config.WithFeaturesPackage("internal/features"),
		config.WithMainTemplate(mainTemplate),
		config.WithTerraformPluginSDKIncludeList([]string{
			"github.com/deuxfleurs-org/garage-terraform-provider/internal/provider",
		}),
		config.WithDefaultResourceOptions(
			GroupKindOverrides(),
			KindOverrides(),
			RegionAddition(),
			TagsAllRemoval(),
		),
	)

	// Add external name configurations
	for name, externalName := range ExternalNameConfigs {
		if r, ok := pc.Resources[name]; ok {
			r.ExternalName = externalName
		}
	}

	// Register resource configurators
	for _, configure := range []func(provider *config.Provider){
		bucket.Configure,
		key.Configure,
	} {
		configure(pc)
	}

	pc.ConfigureResources()
	return pc
}

// GroupKindOverrides returns the default group and kind calculation logic
func GroupKindOverrides() config.ResourceOption {
	return func(r *config.Resource) {
		if r.ShortGroup == "" {
			r.ShortGroup = resourcePrefix
		}
	}
}

// KindOverrides returns the default kind calculation logic
func KindOverrides() config.ResourceOption {
	return func(r *config.Resource) {
		// Keep the Kind as configured by individual resource configurators
	}
}

// RegionAddition adds region support if needed
func RegionAddition() config.ResourceOption {
	return func(r *config.Resource) {
		// Garage doesn't use regions, so this is a no-op
	}
}

// TagsAllRemoval removes tags_all field which is AWS-specific
func TagsAllRemoval() config.ResourceOption {
	return func(r *config.Resource) {
		// Garage doesn't use tags_all, so this is a no-op
	}
}

// mainTemplate is the template for the main.go file
const mainTemplate = `// Code generated by upjet. DO NOT EDIT.

package main

import (
	"context"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/alecthomas/kingpin.v2"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/tools/leaderelection/resourcelock"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	"sigs.k8s.io/controller-runtime/pkg/webhook"

	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/feature"
	"github.com/crossplane/crossplane-runtime/pkg/logging"
	"github.com/crossplane/crossplane-runtime/pkg/ratelimiter"

	"github.com/kikokikok/provider-garage/internal/clients"
	"github.com/kikokikok/provider-garage/internal/controller"
	"github.com/kikokikok/provider-garage/internal/features"
)

func main() {
	var (
		app            = kingpin.New(filepath.Base(os.Args[0]), "Garage Crossplane provider").DefaultEnvars()
		debug          = app.Flag("debug", "Run with debug logging.").Short('d').Bool()
		syncInterval   = app.Flag("sync", "Sync interval for controllers.").Short('s').Default("1h").Duration()
		pollInterval   = app.Flag("poll", "Poll interval for managed resources.").Default("1m").Duration()
		leaderElection = app.Flag("leader-election", "Use leader election for controllers.").Short('l').Default("false").Envar("LEADER_ELECTION").Bool()
		maxReconcileRate = app.Flag("max-reconcile-rate", "Maximum rate of reconciliation per controller.").Default("10").Int()
	)
	kingpin.MustParse(app.Parse(os.Args[1:]))

	zl := zap.New(zap.UseDevMode(*debug))
	log := logging.NewLogrLogger(zl.WithName("provider-garage"))
	ctrl.SetLogger(zl)

	cfg, err := ctrl.GetConfig()
	kingpin.FatalIfError(err, "Cannot get API server rest config")

	mgr, err := ctrl.NewManager(cfg, ctrl.Options{
		Cache: cache.Options{
			SyncPeriod: syncInterval,
		},
		WebhookServer: webhook.NewServer(webhook.Options{
			CertDir: "/webhook/certs",
		}),
		LeaderElection:   *leaderElection,
		LeaderElectionID: "crossplane-leader-election-provider-garage",
		LeaseDuration:    func() *time.Duration { d := 60 * time.Second; return &d }(),
		RenewDeadline:    func() *time.Duration { d := 50 * time.Second; return &d }(),
		LeaderElectionResourceLock: resourcelock.LeasesResourceLock,
	})
	kingpin.FatalIfError(err, "Cannot create controller manager")

	o := controller.Options{
		Logger:                  log,
		MaxConcurrentReconciles: *maxReconcileRate,
		PollInterval:            *pollInterval,
		GlobalRateLimiter:       ratelimiter.NewGlobal(*maxReconcileRate),
		Features:                &feature.Flags{},
	}

	kingpin.FatalIfError(features.Setup(mgr, o), "Cannot setup feature flags")
	kingpin.FatalIfError(controller.Setup(mgr, o), "Cannot setup controllers")
	kingpin.FatalIfError(mgr.Start(ctrl.SetupSignalHandler()), "Cannot start controller manager")
}
`
