---
# Example Garage Key resource
# This creates a namespaced managed resource for a Garage access key
apiVersion: key.garage.crossplane.io/v1alpha1
kind: Key
metadata:
  name: example-key
  namespace: default
spec:
  forProvider:
    # Name for the access key
    name: my-example-key
  providerConfigRef:
    name: default
  # Connection secret will contain access_key_id and secret_access_key
  writeConnectionSecretToRef:
    name: example-key-credentials
    namespace: default
---
# Example KeyAccess resource
# This grants the key access to a specific bucket
apiVersion: key.garage.crossplane.io/v1alpha1
kind: KeyAccess
metadata:
  name: example-key-access
  namespace: default
spec:
  forProvider:
    # Reference to the Key resource
    keyIdRef:
      name: example-key
    # Reference to the Bucket resource
    bucketIdRef:
      name: example-bucket
    # Permissions for the key on this bucket
    read: true
    write: true
    owner: false
  providerConfigRef:
    name: default
