---
# Example Crossplane v2 XRD for GarageBucket
# This demonstrates how to create a v2-compatible XRD using namespaced resources
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: garagebuckets.s3.example.com
spec:
  # IMPORTANT: scope is Namespaced for v2 compatibility
  scope: Namespaced
  group: s3.example.com
  names:
    kind: GarageBucket
    plural: garagebuckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Bucket name/alias
              bucketName:
                type: string
                description: The name/global alias for the S3 bucket
              # Whether to create an access key automatically
              createAccessKey:
                type: boolean
                default: true
                description: Whether to automatically create an access key with full permissions
              # Optional: Key permissions
              permissions:
                type: object
                properties:
                  read:
                    type: boolean
                    default: true
                  write:
                    type: boolean
                    default: true
                  owner:
                    type: boolean
                    default: false
            required:
            - bucketName
          status:
            type: object
            properties:
              # Bucket endpoint information
              endpoint:
                type: string
              # Bucket name
              bucketName:
                type: string
              # Key name if created
              keyName:
                type: string
---
# Example Composition for GarageBucket using Function Pipeline
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: garagebuckets.s3.example.com
  labels:
    provider: garage
    crossplane.io/xrd: garagebuckets.s3.example.com
spec:
  compositeTypeRef:
    apiVersion: s3.example.com/v1alpha1
    kind: GarageBucket
  
  # Use Pipeline mode for flexible composition
  mode: Pipeline
  
  pipeline:
  - step: render-resources
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          # Create the Garage Bucket (namespaced!)
          apiVersion: bucket.garage.crossplane.io/v1alpha1
          kind: Bucket
          metadata:
            name: {{ .observed.composite.resource.spec.bucketName }}
            annotations:
              crossplane.io/external-name: {{ .observed.composite.resource.spec.bucketName }}
          spec:
            forProvider:
              globalAlias: {{ .observed.composite.resource.spec.bucketName }}
            providerConfigRef:
              name: default
          {{- if .observed.composite.resource.spec.createAccessKey }}
          ---
          # Create an Access Key (namespaced!)
          apiVersion: key.garage.crossplane.io/v1alpha1
          kind: Key
          metadata:
            name: {{ .observed.composite.resource.spec.bucketName }}-key
            annotations:
              crossplane.io/external-name: {{ .observed.composite.resource.spec.bucketName }}-key
          spec:
            forProvider:
              name: {{ .observed.composite.resource.spec.bucketName }}-key
            providerConfigRef:
              name: default
            writeConnectionSecretToRef:
              name: {{ .observed.composite.resource.metadata.name }}-credentials
          ---
          # Grant Key Access to Bucket (namespaced!)
          apiVersion: key.garage.crossplane.io/v1alpha1
          kind: KeyAccess
          metadata:
            name: {{ .observed.composite.resource.spec.bucketName }}-access
          spec:
            forProvider:
              keyIdRef:
                name: {{ .observed.composite.resource.spec.bucketName }}-key
              bucketIdRef:
                name: {{ .observed.composite.resource.spec.bucketName }}
              read: {{ default true .observed.composite.resource.spec.permissions.read }}
              write: {{ default true .observed.composite.resource.spec.permissions.write }}
              owner: {{ default false .observed.composite.resource.spec.permissions.owner }}
            providerConfigRef:
              name: default
          {{- end }}
  
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready
