# crossplane.yaml - Crossplane v2+ Provider Package Metadata
apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-garage
  annotations:
    meta.crossplane.io/maintainer: Kyriba Cloud Platform Team <christian.klat@kyriba.com>
    meta.crossplane.io/source: github.com/kikokikok/garage-crossplane-provider
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Crossplane provider for Garage object storage (S3-compatible).
      Supports bucket management and key creation for Garage deployments.
    meta.crossplane.io/readme: |
      Provider Garage is a Crossplane provider for managing Garage object
      storage resources. It supports bucket management and access key creation
      for Garage deployments.
spec:
  controller:
    image: ghcr.io/kikokikok/garage-crossplane-provider:latest
  crossplane:
    version: ">=v1.12.1-0"
